<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<div class="mi-topbar"><div class="mi-container"><span class="mi-dot"></span><span>12 advisors online now · Private written readings from $11.90</span></div></div>
<header class="mi-header"><div class="mi-container mi-nav"><a class="mi-brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="mi-brand-mark">✦</span><span><?php bloginfo('name'); ?></span></a><nav class="mi-menu"><a href="#topics">Topics</a><a href="#how">How it works</a><a href="#advisors">Advisors</a><a href="#pricing">Pricing</a><a class="mi-button mi-button--ghost" href="#start">Ask a question</a></nav></div></header>
<main>
<section id="start" class="mi-hero"><div class="mi-container mi-hero-grid"><div><div class="mi-kicker">Confidential online fortune reading</div><h1 class="mi-title">Ask your question. <span>Get clarity.</span></h1><p class="mi-lead">Choose a topic, write one clear question, pick a package, and send your private reading request in a guided flow.</p><div class="mi-hero-actions"><a class="mi-button mi-button--orange" href="#start">Start from $11.90</a><a class="mi-button mi-button--ghost" href="#how">How it works</a></div><div class="mi-trust-row"><div class="mi-trust"><strong>4.9★</strong><span>average rating</span></div><div class="mi-trust"><strong>24h</strong><span>typical delivery</span></div><div class="mi-trust"><strong>100%</strong><span>private reading</span></div></div></div>
<aside class="mi-app-card" data-reading-flow><div class="mi-app-head"><div class="mi-agent"><div class="mi-avatar">M</div><div><strong>Mira</strong><span><i class="mi-dot"></i> Online advisor</span></div></div><div class="mi-rating">★★★★★</div></div><div class="mi-form"><div class="mi-progress"><span data-progress></span></div><p class="mi-step-label" data-step-text>Step 1 of 3</p>
<div data-step-panel="1"><h2 class="mi-question">What do you need clarity about?</h2><div class="mi-choice-grid"><button class="mi-choice is-active" data-topic="Love"><strong>Love</strong><span>Crush, ex, relationship, future</span></button><button class="mi-choice" data-topic="Career"><strong>Career</strong><span>Job, money, business timing</span></button><button class="mi-choice" data-topic="Decision"><strong>Decision</strong><span>Choose between two paths</span></button><button class="mi-choice" data-topic="Future"><strong>Future</strong><span>General guidance and direction</span></button></div></div>
<div data-step-panel="2" hidden><h2 class="mi-question">Write your question.</h2><textarea class="mi-textarea" data-question-input placeholder="Example: Will my ex contact me again? What should I know about this connection?"></textarea><div class="mi-form-footer"><button class="mi-button mi-button--ghost" data-prev-step="1" type="button">Back</button><button class="mi-button" data-next-step="3" type="button">Continue</button></div></div>
<div data-step-panel="3" hidden><h2 class="mi-question">Choose your reading.</h2><div class="mi-choice-grid"><button class="mi-choice" data-package="Single Question" data-price="$11.90"><strong>$11.90</strong><span>Single focused answer</span></button><button class="mi-choice is-active" data-package="Two Questions" data-price="$18.90"><strong>$18.90</strong><span>Best first order</span></button><button class="mi-choice" data-package="Deep Reading" data-price="$39"><strong>$39</strong><span>Detailed written guidance</span></button><button class="mi-choice" data-package="Love Clarity" data-price="$29"><strong>$29</strong><span>Relationship-focused reading</span></button></div><div class="mi-card" style="margin-top:14px"><p class="mi-step-label">Order summary</p><p><strong>Topic:</strong> <span data-summary-topic>Love</span></p><p><strong>Package:</strong> <span data-summary-package>Two Questions · $18.90</span></p><p><strong>Question:</strong> <span data-summary-question>Your question will appear here.</span></p></div><div class="mi-form-footer"><button class="mi-button mi-button--ghost" data-prev-step="2" type="button">Back</button><a class="mi-button mi-button--orange" data-final-link href="mailto:hello@example.com">Send request</a></div></div>
<p class="mi-secure" style="margin-top:14px">🔒 Your question stays private. Replace email with checkout or WhatsApp later.</p></div></aside></div></section>
<section class="mi-proof-band"><div class="mi-container mi-proof-grid"><div class="mi-proof-item"><strong>18k+</strong><span>questions answered</span></div><div class="mi-proof-item"><strong>92%</strong><span>felt clearer after reading</span></div><div class="mi-proof-item"><strong>7 min</strong><span>average order time</span></div><div class="mi-proof-item"><strong>4.9/5</strong><span>customer rating</span></div></div></section>
<section id="topics" class="mi-section"><div class="mi-container"><div class="mi-section-head"><p class="mi-eyebrow">Reading topics</p><h2 class="mi-section-title">Built around the questions people actually ask.</h2><p class="mi-section-copy">The first screen now works like a consultation intake, not a normal brochure page.</p></div><div class="mi-cards"><article class="mi-card"><div class="mi-icon">💗</div><h3>Love reading</h3><p>For attraction, ex contact, hidden feelings, commitment and relationship direction.</p></article><article class="mi-card"><div class="mi-icon">💼</div><h3>Career reading</h3><p>For job offers, money decisions, business timing and whether to make a move.</p></article><article class="mi-card"><div class="mi-icon">🔮</div><h3>Future guidance</h3><p>For general direction, energy patterns, near-future opportunities and warnings.</p></article></div></div></section>
<section id="how" class="mi-flow"><div class="mi-container"><div class="mi-section-head"><p class="mi-eyebrow">How it works</p><h2 class="mi-section-title">From question to answer in four simple steps.</h2><p class="mi-section-copy">Topic, question, package, private delivery.</p></div><div class="mi-steps"><div class="mi-step"><h3>Choose topic</h3><p>Love, career, timing, decision or general future.</p></div><div class="mi-step"><h3>Write question</h3><p>The visitor enters one clear question and optional background.</p></div><div class="mi-step"><h3>Select package</h3><p>Single question, two questions or deep reading.</p></div><div class="mi-step"><h3>Receive answer</h3><p>A private written reading with clear next steps.</p></div></div></div></section>
<section id="advisors" class="mi-section"><div class="mi-container"><div class="mi-section-head"><p class="mi-eyebrow">Advisor cards</p><h2 class="mi-section-title">Human trust before payment.</h2><p class="mi-section-copy">Advisor profiles make the service feel more real and closer to a consultation platform.</p></div><div class="mi-advisors"><article class="mi-advisor"><div class="mi-advisor-top"><div class="mi-avatar">M</div><div><h3>Mira</h3><span class="mi-rating">4.9 ★</span></div></div><p>Warm relationship readings with direct, practical advice.</p><div class="mi-tags"><span class="mi-tag">Love</span><span class="mi-tag">No contact</span><span class="mi-tag">Timing</span></div></article><article class="mi-advisor"><div class="mi-advisor-top"><div class="mi-avatar">A</div><div><h3>Astra</h3><span class="mi-rating">4.8 ★</span></div></div><p>Career, money and business energy readings for key decisions.</p><div class="mi-tags"><span class="mi-tag">Career</span><span class="mi-tag">Money</span><span class="mi-tag">Business</span></div></article><article class="mi-advisor"><div class="mi-advisor-top"><div class="mi-avatar">L</div><div><h3>Luna</h3><span class="mi-rating">5.0 ★</span></div></div><p>Future-focused guidance for confusing life transitions.</p><div class="mi-tags"><span class="mi-tag">Future</span><span class="mi-tag">Energy</span><span class="mi-tag">Decision</span></div></article></div></div></section>
<section id="pricing" class="mi-section"><div class="mi-container"><div class="mi-section-head"><p class="mi-eyebrow">Pricing</p><h2 class="mi-section-title">Low-friction offers for first-time buyers.</h2><p class="mi-section-copy">Use these as WooCommerce products or connect buttons to Stripe, PayPal, WhatsApp or a form.</p></div><div class="mi-pricing"><article class="mi-price-card"><h3>1 Question</h3><p>Best for one focused concern.</p><div class="mi-price">$11.90</div><ul><li>One written answer</li><li>Advice and likely direction</li><li>Private delivery</li></ul><a class="mi-button mi-button--ghost" href="#start">Choose</a></article><article class="mi-price-card featured"><h3>2 Questions</h3><p>Most popular first order.</p><div class="mi-price">$18.90</div><ul><li>Two related answers</li><li>Pattern summary</li><li>Recommended next step</li></ul><a class="mi-button mi-button--orange" href="#start">Start now</a></article><article class="mi-price-card"><h3>Deep Reading</h3><p>For complex situations.</p><div class="mi-price">$39</div><ul><li>Detailed reading</li><li>Multiple angles</li><li>Action guidance</li></ul><a class="mi-button mi-button--ghost" href="#start">Choose</a></article></div></div></section>
<section class="mi-cta"><div class="mi-container"><div class="mi-cta-box"><div><h2>Start with one clear question.</h2><p>The flow now captures topic, question and package before the final request.</p></div><a class="mi-button mi-button--orange" href="#start">Ask now</a></div></div></section>
</main>
<footer class="mi-footer"><div class="mi-container"><p>© <?php echo esc_html(date('Y')); ?> <?php bloginfo('name'); ?>. For entertainment and personal reflection.</p><p>Privacy · Terms · Contact</p></div></footer>
<?php wp_footer(); ?>
</body>
</html>
